"""create_superadmin_organizations_table

Revision ID: f02125977068
Revises: c3d4e5f6a7b8
Create Date: 2026-03-06 21:54:09.520583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02125977068'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superadmin_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=300), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=True),
    sa.Column('rfc', sa.String(length=13), nullable=False),
    sa.Column('regimen_fiscal', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('sitio_web', sa.String(length=200), nullable=True),
    sa.Column('calle', sa.String(length=200), nullable=True),
    sa.Column('numero_exterior', sa.String(length=50), nullable=True),
    sa.Column('numero_interior', sa.String(length=50), nullable=True),
    sa.Column('colonia', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=10), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('color_primario', sa.String(length=7), nullable=True),
    sa.Column('color_secundario', sa.String(length=7), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('notas_internas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superadmin_organizations_id'), 'superadmin_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_superadmin_organizations_rfc'), 'superadmin_organizations', ['rfc'], unique=True)
    op.create_index(op.f('ix_superadmin_organizations_user_id'), 'superadmin_organizations', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_superadmin_organizations_user_id'), table_name='superadmin_organizations')
    op.drop_index(op.f('ix_superadmin_organizations_rfc'), table_name='superadmin_organizations')
    op.drop_index(op.f('ix_superadmin_organizations_id'), table_name='superadmin_organizations')
    op.drop_table('superadmin_organizations')
    # ### end Alembic commands ###
