"""update companies fields

Revision ID: d529e184c99c
Revises: 00376b17f326
Create Date: 2026-02-22 20:01:10.625723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd529e184c99c'
down_revision: Union[str, None] = '00376b17f326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('razon_social', sa.String(length=300), nullable=False))
    op.add_column('companies', sa.Column('nombre_comercial', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('telefono', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('direccion', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('ciudad', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('estado', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('codigo_postal', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('rpu', sa.String(length=50), nullable=False))
    op.add_column('companies', sa.Column('tipo_suministro', sa.String(length=50), nullable=False))
    op.add_column('companies', sa.Column('tension_suministro', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('demanda_contratada_kw', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('demanda_maxima_kw', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('factor_carga', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('factor_potencia', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('consumo_mensual_kwh', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('costo_mensual_aproximado', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('nombre_centro_carga', sa.String(length=200), nullable=True))
    op.add_column('companies', sa.Column('ubicacion_centro_carga', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('clasificacion', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('notas', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('companies', 'rfc',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=13),
               nullable=False)
    op.create_index(op.f('ix_companies_clasificacion'), 'companies', ['clasificacion'], unique=False)
    op.create_index(op.f('ix_companies_rfc'), 'companies', ['rfc'], unique=True)
    op.create_index(op.f('ix_companies_rpu'), 'companies', ['rpu'], unique=True)
    op.drop_column('companies', 'voltage_level')
    op.drop_column('companies', 'installed_capacity_kw')
    op.drop_column('companies', 'region')
    op.drop_column('companies', 'has_generation')
    op.drop_column('companies', 'contact_name')
    op.drop_column('companies', 'contact_email')
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.add_column('companies', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('contact_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('has_generation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('installed_capacity_kw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('voltage_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_rpu'), table_name='companies')
    op.drop_index(op.f('ix_companies_rfc'), table_name='companies')
    op.drop_index(op.f('ix_companies_clasificacion'), table_name='companies')
    op.alter_column('companies', 'rfc',
               existing_type=sa.String(length=13),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('companies', 'is_active')
    op.drop_column('companies', 'notas')
    op.drop_column('companies', 'clasificacion')
    op.drop_column('companies', 'ubicacion_centro_carga')
    op.drop_column('companies', 'nombre_centro_carga')
    op.drop_column('companies', 'costo_mensual_aproximado')
    op.drop_column('companies', 'consumo_mensual_kwh')
    op.drop_column('companies', 'factor_potencia')
    op.drop_column('companies', 'factor_carga')
    op.drop_column('companies', 'demanda_maxima_kw')
    op.drop_column('companies', 'demanda_contratada_kw')
    op.drop_column('companies', 'tension_suministro')
    op.drop_column('companies', 'tipo_suministro')
    op.drop_column('companies', 'rpu')
    op.drop_column('companies', 'codigo_postal')
    op.drop_column('companies', 'estado')
    op.drop_column('companies', 'ciudad')
    op.drop_column('companies', 'direccion')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'telefono')
    op.drop_column('companies', 'nombre_comercial')
    op.drop_column('companies', 'razon_social')
    # ### end Alembic commands ###
