"""add_projects_module

Revision ID: 359d44c42b9d
Revises: 20260223_0100
Create Date: 2026-02-23 05:30:41.946180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '359d44c42b9d'
down_revision: Union[str, None] = '20260223_0100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.Enum('OBLIGATION', 'CUSTOM', name='tasktype'), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NO_INICIADO', 'EN_PROGRESO', 'COMPLETADO', 'CERRADO', name='taskstatus'), nullable=False),
    sa.Column('assignee_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['compliance_requirements.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_tasks_id'), 'project_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_project_tasks_project_id'), 'project_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_status'), 'project_tasks', ['status'], unique=False)
    op.create_table('task_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_activity_logs_id'), 'task_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_task_activity_logs_task_id'), 'task_activity_logs', ['task_id'], unique=False)
    op.create_table('task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comments_id'), 'task_comments', ['id'], unique=False)
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.create_table('task_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.Enum('MEDICION', 'FOTO', 'INFORME', 'BITACORA', 'DICTAMEN', 'MANUAL', 'OTRO', name='evidencetype'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['project_tasks.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_evidences_id'), 'task_evidences', ['id'], unique=False)
    op.create_index(op.f('ix_task_evidences_task_id'), 'task_evidences', ['task_id'], unique=False)
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_table('tasks')
    op.alter_column('companies', 'rpu',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('companies', 'tipo_suministro',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('company_classifications', 'tipo_centro_carga',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('TIPO_A', 'TIPO_B', 'TIPO_C', name='tipocentrocarga'),
               existing_nullable=False)
    op.drop_index(op.f('ix_company_classifications_company_id'), table_name='company_classifications')
    op.drop_index(op.f('ix_company_classifications_tenant_id'), table_name='company_classifications')
    op.create_index(op.f('ix_company_classifications_id'), 'company_classifications', ['id'], unique=False)
    op.drop_index(op.f('ix_compliance_audit_logs_company_id'), table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_created_at'), table_name='compliance_audit_logs')
    op.drop_index(op.f('ix_compliance_audit_logs_tenant_id'), table_name='compliance_audit_logs')
    op.create_index(op.f('ix_compliance_audit_logs_id'), 'compliance_audit_logs', ['id'], unique=False)
    op.alter_column('compliance_requirements', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('compliance_requirements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('compliance_requirements_codigo_key'), 'compliance_requirements', type_='unique')
    op.drop_index(op.f('ix_compliance_requirements_codigo'), table_name='compliance_requirements')
    op.create_index(op.f('ix_compliance_requirements_codigo'), 'compliance_requirements', ['codigo'], unique=True)
    op.create_index(op.f('ix_compliance_requirements_id'), 'compliance_requirements', ['id'], unique=False)
    op.alter_column('compliance_rules', 'tipo_centro_carga',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('TIPO_A', 'TIPO_B', 'TIPO_C', name='tipocentrocarga'),
               existing_nullable=False)
    op.alter_column('compliance_rules', 'estado_aplicabilidad',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('APLICA', 'NO_APLICA', 'APLICA_RDC', 'APLICA_TIC', name='estadoaplicabilidad'),
               existing_nullable=False)
    op.alter_column('compliance_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_compliance_rules_requirement_id'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_tipo'), table_name='compliance_rules')
    op.create_index(op.f('ix_compliance_rules_id'), 'compliance_rules', ['id'], unique=False)
    op.alter_column('documents', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tipo_documento'), table_name='documents')
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.add_column('projects', sa.Column('project_type', sa.Enum('AUDITORIA', 'CORRECTIVO', 'MANTENIMIENTO', 'REVISION_RUTINA', 'TC', name='projecttype'), nullable=False))
    op.add_column('projects', sa.Column('priority', sa.Enum('BAJA', 'MEDIA', 'ALTA', 'CRITICA', name='priority'), nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ABIERTO', 'EN_PROGRESO', 'COMPLETADO', 'CERRADO', name='projectstatus'),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_project_type'), 'projects', ['project_type'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_project_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('ABIERTO', 'EN_PROGRESO', 'COMPLETADO', 'CERRADO', name='projectstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.drop_column('projects', 'updated_by')
    op.drop_column('projects', 'created_by')
    op.drop_column('projects', 'closed_at')
    op.drop_column('projects', 'completed_at')
    op.drop_column('projects', 'due_date')
    op.drop_column('projects', 'start_date')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'project_type')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.create_index(op.f('ix_documents_tipo_documento'), 'documents', ['tipo_documento'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_compliance_rules_id'), table_name='compliance_rules')
    op.create_index(op.f('ix_compliance_rules_tipo'), 'compliance_rules', ['tipo_centro_carga'], unique=False)
    op.create_index(op.f('ix_compliance_rules_requirement_id'), 'compliance_rules', ['requirement_id'], unique=False)
    op.alter_column('compliance_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('compliance_rules', 'estado_aplicabilidad',
               existing_type=sa.Enum('APLICA', 'NO_APLICA', 'APLICA_RDC', 'APLICA_TIC', name='estadoaplicabilidad'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('compliance_rules', 'tipo_centro_carga',
               existing_type=sa.Enum('TIPO_A', 'TIPO_B', 'TIPO_C', name='tipocentrocarga'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_compliance_requirements_id'), table_name='compliance_requirements')
    op.drop_index(op.f('ix_compliance_requirements_codigo'), table_name='compliance_requirements')
    op.create_index(op.f('ix_compliance_requirements_codigo'), 'compliance_requirements', ['codigo'], unique=False)
    op.create_unique_constraint(op.f('compliance_requirements_codigo_key'), 'compliance_requirements', ['codigo'], postgresql_nulls_not_distinct=False)
    op.alter_column('compliance_requirements', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('compliance_requirements', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_compliance_audit_logs_id'), table_name='compliance_audit_logs')
    op.create_index(op.f('ix_compliance_audit_logs_tenant_id'), 'compliance_audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_compliance_audit_logs_created_at'), 'compliance_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_compliance_audit_logs_company_id'), 'compliance_audit_logs', ['company_id'], unique=False)
    op.drop_index(op.f('ix_company_classifications_id'), table_name='company_classifications')
    op.create_index(op.f('ix_company_classifications_tenant_id'), 'company_classifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_company_classifications_company_id'), 'company_classifications', ['company_id'], unique=False)
    op.alter_column('company_classifications', 'tipo_centro_carga',
               existing_type=sa.Enum('TIPO_A', 'TIPO_B', 'TIPO_C', name='tipocentrocarga'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('companies', 'tipo_suministro',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('companies', 'rpu',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('tasks_project_id_fkey')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tasks_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.drop_index(op.f('ix_task_evidences_task_id'), table_name='task_evidences')
    op.drop_index(op.f('ix_task_evidences_id'), table_name='task_evidences')
    op.drop_table('task_evidences')
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.drop_index(op.f('ix_task_comments_id'), table_name='task_comments')
    op.drop_table('task_comments')
    op.drop_index(op.f('ix_task_activity_logs_task_id'), table_name='task_activity_logs')
    op.drop_index(op.f('ix_task_activity_logs_id'), table_name='task_activity_logs')
    op.drop_table('task_activity_logs')
    op.drop_index(op.f('ix_project_tasks_status'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_project_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_id'), table_name='project_tasks')
    op.drop_table('project_tasks')
    # ### end Alembic commands ###
